gyrinx/core/urls.py
from django.urls import path

import gyrinx.core.views

from .views import battle, print_config, vehicle
from .views.campaign import actions as campaign_actions
from .views.campaign import assets as campaign_assets
from .views.campaign import attributes as campaign_attributes
from .views.campaign import battles as campaign_battles
from .views.campaign import captured as campaign_captured
from .views.campaign import copy as campaign_copy
from .views.campaign import packs as campaign_packs
from .views.campaign import crud as campaign_crud
from .views.campaign import lifecycle as campaign_lifecycle
from .views.campaign import lists as campaign_lists
from .views.campaign import resources as campaign_resources
from .views.campaign import sub_assets as campaign_sub_assets
from .views.campaign import views as campaign_views
from .views.fighter import advancements as fighter_advancements
from .views.fighter import counters as fighter_counters
from .views.fighter import crud as fighter_crud
from .views.fighter import equipment as fighter_equipment
from .views.fighter import narrative as fighter_narrative
from .views.fighter import powers as fighter_powers
from .views.fighter import rules as fighter_rules
from .views.fighter import skills as fighter_skills
from .views.fighter import state as fighter_state
from .views.fighter import stats as fighter_stats
from .views.fighter import xp as fighter_xp
from .views.list import attributes as list_attributes
from .views.list import invitations as list_invitations
from .views.list import views as list_views
from .views import pack as pack_views

# Name new URLs like this:
# * Transaction pages: noun[-noun]-verb
# * Index pages should pluralize the noun: noun[-noun]s
# * Detail pages should be singular: noun[-noun]

app_name = "core"
urlpatterns = [
    path("", gyrinx.core.views.index, name="index"),
    path("accounts/", gyrinx.core.views.account_home, name="account_home"),
    path(
        "accounts/change-username/",
        gyrinx.core.views.change_username,
        name="change-username",
    ),
    path("dice/", gyrinx.core.views.dice, name="dice"),
    path("lists/", list_views.ListsListView.as_view(), name="lists"),
    path("lists/new/packs", list_views.new_list_packs, name="lists-new-packs"),
    path("lists/new", list_views.new_list, name="lists-new"),
    path("list/<id>", list_views.ListDetailView.as_view(), name="list"),
    path(
        "list/<id>/perf",
        list_views.ListPerformanceView.as_view(),
        name="list-performance",
    ),
    path(
        "list/<id>/about", list_views.ListAboutDetailView.as_view(), name="list-about"
    ),
    path("list/<id>/archive", list_views.archive_list, name="list-archive"),
    path("list/<id>/show-stash", list_views.show_stash, name="list-show-stash"),
    path(
        "list/<id>/refresh-cost", list_views.refresh_list_cost, name="list-refresh-cost"
    ),
    path("list/<id>/edit", list_views.edit_list, name="list-edit"),
    path("list/<id>/packs", pack_views.list_packs_manage, name="list-packs"),
    path("list/<id>/credits", list_views.edit_list_credits, name="list-credits-edit"),
    path("list/<id>/clone", list_views.clone_list, name="list-clone"),
    path(
        "list/<id>/invitations",
        list_invitations.list_invitations,
        name="list-invitations",
    ),
    path(
        "list/<id>/invitations/<invitation_id>/accept",
        list_invitations.accept_invitation,
        name="invitation-accept",
    ),
    path(
        "list/<id>/invitations/<invitation_id>/decline",
        list_invitations.decline_invitation,
        name="invitation-decline",
    ),
    path(
        "list/<id>/fighters/new", fighter_crud.new_list_fighter, name="list-fighter-new"
    ),
    path("list/<id>/vehicles/new", vehicle.new_vehicle, name="list-vehicle-new"),
    path(
        "list/<id>/vehicles/new/select",
        vehicle.vehicle_select,
        name="list-vehicle-select",
    ),
    path("list/<id>/vehicles/new/crew", vehicle.vehicle_crew, name="list-vehicle-crew"),
    path(
        "list/<id>/vehicles/new/confirm",
        vehicle.vehicle_confirm,
        name="list-vehicle-confirm",
    ),
    path(
        "list/<id>/fighters/archived",
        fighter_crud.ListArchivedFightersView.as_view(),
        name="list-archived-fighters",
    ),
    path(
        "list/<id>/fighter/<fighter_id>",
        fighter_crud.edit_list_fighter,
        name="list-fighter-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/clone",
        fighter_crud.clone_list_fighter,
        name="list-fighter-clone",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills",
        fighter_skills.edit_list_fighter_skills,
        name="list-fighter-skills-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills/<skill_id>/toggle",
        fighter_skills.toggle_list_fighter_skill,
        name="list-fighter-skill-toggle",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills/add",
        fighter_skills.add_list_fighter_skill,
        name="list-fighter-skill-add",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills/<skill_id>/remove",
        fighter_skills.remove_list_fighter_skill,
        name="list-fighter-skill-remove",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules",
        fighter_rules.edit_list_fighter_rules,
        name="list-fighter-rules-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules/<rule_id>/toggle",
        fighter_rules.toggle_list_fighter_rule,
        name="list-fighter-rule-toggle",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules/add",
        fighter_rules.add_list_fighter_rule,
        name="list-fighter-rule-add",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules/<rule_id>/remove",
        fighter_rules.remove_list_fighter_rule,
        name="list-fighter-rule-remove",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/powers",
        fighter_powers.edit_list_fighter_powers,
        name="list-fighter-powers-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/narrative",
        fighter_narrative.edit_list_fighter_narrative,
        name="list-fighter-narrative-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/info",
        fighter_narrative.edit_list_fighter_info,
        name="list-fighter-info-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/stats",
        fighter_stats.list_fighter_stats_edit,
        name="list-fighter-stats-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear",
        fighter_equipment.edit_list_fighter_equipment,
        name="list-fighter-gear-edit",
        kwargs=dict(
            is_weapon=False,
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/cost",
        fighter_equipment.edit_list_fighter_assign_cost,
        name="list-fighter-gear-cost-edit",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-cost-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/delete",
        fighter_equipment.delete_list_fighter_assign,
        name="list-fighter-gear-delete",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-delete",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/reassign",
        fighter_equipment.reassign_list_fighter_equipment,
        name="list-fighter-gear-reassign",
        kwargs=dict(
            is_weapon=False,
            back_name="core:list-fighter-gear-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/sell",
        fighter_equipment.sell_list_fighter_equipment,
        name="list-fighter-equipment-sell",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/upgrade",
        fighter_equipment.edit_list_fighter_weapon_upgrade,
        name="list-fighter-gear-upgrade-edit",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-upgrade-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/upgrade/<upgrade_id>/delete",
        fighter_equipment.delete_list_fighter_gear_upgrade,
        name="list-fighter-gear-upgrade-delete",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-upgrade-delete",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/disable",
        fighter_equipment.disable_list_fighter_default_assign,
        name="list-fighter-gear-default-disable",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-default-disable",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/convert",
        fighter_equipment.convert_list_fighter_default_assign,
        name="list-fighter-gear-default-convert",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-default-convert",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/disable",
        fighter_equipment.disable_list_fighter_default_assign,
        name="list-fighter-weapons-default-disable",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapons-default-disable",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/convert",
        fighter_equipment.convert_list_fighter_default_assign,
        name="list-fighter-weapons-default-convert",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapons-default-convert",
        ),

gyrinx/core/templates/core/list/list_invitations.html
{% extends "core/layouts/base.html" %}
{% load static %}
{% block title %}
    Invitations - {{ list.name }}
{% endblock title %}
{% block content %}
    <div class="col-12 col-xl-6">
        <div class="mb-3">{% include "core/includes/back_to_list.html" with list=list text="Back to list" %}</div>
        <h2 class="mb-3">Campaign Invitations</h2>
        {% if invitations %}
            <div class="mb-3">
                {% for invitation in invitations %}
                    <div class="border rounded p-3 mb-3">
                        <div class="d-flex justify-content-between align-items-start mb-2">
                            <div>
                                <h5 class="mb-1">
                                    <a href="{% url 'core:campaign' invitation.campaign.id %}" class="">{{ invitation.campaign.name }}</a>
                                    <span class="fs-7">{% include "core/campaign/includes/status.html" with campaign=invitation.campaign %}</span>
                                </h5>
                                <p class="text-secondary mb-0">
                                    <small>From: {{ invitation.campaign.owner.username }}</small>
                                </p>
                                {% if invitation.message %}<p class="mt-2 mb-0">{{ invitation.message }}</p>{% endif %}
                            </div>
                            <small class="text-secondary">{{ invitation.created|date:"M d, Y" }}</small>
                        </div>
                        <div class="mt-3">
                            <form method="post"
                                  action="{% url 'core:invitation-accept' list.id invitation.id %}"
                                  class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success btn-sm">Accept</button>
                            </form>
                            <form method="post"
                                  action="{% url 'core:invitation-decline' list.id invitation.id %}"
                                  class="d-inline ms-2">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-link text-secondary btn-sm">Decline</button>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>
                No pending invitations.
                {% if list.is_list_building and list.active_campaign_clones|length %}
                    <a href="{% url 'core:list-campaign-clones' list.id %}" class="linked">See campaign gang versions of this list.</a>
                {% endif %}
            </p>
        {% endif %}
    </div>
{% endblock content %}